#---------------------------------------------
# First  simple git action
#---------------------------------------------

name: SImple_Pipeline
env: 
  My_APP_NAME : "My_first_app"
  
  
on: 
  push:
    branches: 
      - master
      
jobs: 
  
  my_job1:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Print hello world 
      run: echo "HELLO WORLD !!!"
      
    - name: run ls -la 
      run : ls -la
    
    - name: print good by
      run : echo "app name is: ${{ env.My_APP_NAME }}"
        
  my_job2:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: first step job2
      run: echo "HELLO FROM JOB 2"
      
    
