#---------------------------------------------
# First  simple git action
#---------------------------------------------

name: SImple_Pipeline
env: 
  APP_NAME : "My_first_app"
on: 
  push:
    branches: 
      - master
      
jobs: 
  
  my_job1:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Print hello world 
      run: echo "HELLO WORLD !!!"
      
    - name: run ls -la & print good by
      run : |
        ls -la
        echo  S{{ env.APP_NAME }}
        
        
  my_job2:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: first step job2
      run: echo "HELLO FROM JOB 2"
      
    
