#---------------------------------------------
# First  simple git action
#---------------------------------------------

name: SImple_Pipeline

env: 
  My_APP_NAME : "My_first_app"
  RELISE_NAME : "My_first_app-${{ github.sha }}"
  
  
on: 
  push:
    branches: 
      - master
      
jobs: 
  
  my_job1:
    runs-on: ubuntu-latest
    
    steps:
    
    
    - name : change env
      run : ${{ env.RELISE_NAME }} = "NEW"
     
    - name: Print env 
      run: echo "env value is ${{ env.RELISE_NAME }}"
      
    - name: Print hello world 
      run: echo "HELLO WORLD !!!"
      
    - name: run ls -la 
      run : ls -la
      
    - name: Git clone 
      uses: actions/checkout@v1
      
    - name: run ls -la 
      run : ls -la
      
    - name: print good by
      run : echo "app name is ${{ env.My_APP_NAME }}"
      
    - name : Run test 1
      run: cat text.txt 1
        
  my_job2:
    runs-on: ubuntu-latest
    needs: [my_job1]
    
    steps:
    
    - name: run ls -la 
      run : ls -la
      
    - name: first step job2
      run: echo "HELLO FROM JOB 2"
      
    - name: first step job2
      run : echo " $LOCAL_VAR "
      env : 
        LOCAL_VAR: "LOCAL_VALUE"
        
    - name: check aws version
      run : echo "Relise name ${{ env.RELISE_NAME }}"
      
    - name: Print env 
      run: echo "env value is ${{ env.RELISE_NAME }}"
      
      
    
