#---------------------------------------------
# First  simple git action
#---------------------------------------------

name: SImple_Pipeline

on: 
  push:
    branches: 
      - master
      
jobs: 
  
  my_job1:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Print hello world 
      run: echo "HELLO WORLD !!!"
    
